name: maggiemacnab1
favicon: null
layout_spectrum: 0.97934
typography_spectrum: 0.36155
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#030303'
    - '#8c93af'
    - '#3d3e38'
    - '#2d74a6'
  brandStrength: 0.0625
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 0.9990792183671147
purpose: []
